### PR TITLE
Update segmentupdates.lua

### PR DESCRIPTION
**Pull request by kaesden**
Updated Location tracking to only track on item acquition for race mode. standard functionality unchanged in casual mode.

### CODE REVIEW

**Review by codemann8 — CHANGES_REQUESTED** [review]
The check for Race Mode should happen instead the method call, not in segmentupdates.lua

**Comment by kaesden** [comment]
updated how changes are implemented as requested.

**Review by codemann8 — CHANGES_REQUESTED** [review]
This is correct, however there are lines that were reordered from the original segmentupdates. And I can't for the life of me figure out how to only merge part of the pull request, I might just take the changed line and manually put it in.

**Comment by kaesden** [comment]
let me just reject this request and revert it and create a clean pull request.

**Pull request closed without merging**
